### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by hoanglvbd** [curvenote/sidenotes#12]
Hi, I implement this algorithm to my project which has over 1000 DOM note lead to bad performance when it's calculating and scrolling.

So if there is any solution we can reduce DOM size but still can get exact position?

**Comment by rowanc1** [comment]
It may be a throttling issue of calling the `placeSidenotes` action too many times. Try putting that in a `lodash.throttle` or similar.

Other solutions:
* If your documents are independent you can place them in different doc trees, and then the place sidenotes function can be called for a subset of the tree.

This function has the placement code:
https://github.com/curvenote/sidenotes/blob/main/src/store/ui/reducers.ts#L54

You could see how many times and why that gets called by your code. Or use it to get the positions.
