### ISSUE TITLE
For vanilla JS, where does the store come from?

### ISSUE THREAD

**Issue by vedantroy** [curvenote/sidenotes#17]
The vanilla JS example references a `store`. Where is the `store` coming from? Is it an import from the sidenotes package?

**Comment by rowanc1** [comment]
This would be a redux store, you can learn about redux here:
https://redux.js.org/introduction/getting-started#basic-example

You can add sidenotes to this store here:
https://github.com/curvenote/sidenotes#redux-state

**Comment by vedantroy** [comment]
Got it. I was hoping sidenotes exported its own redux store that I could use, since I'm not using Redux anywhere else in my application and I don't want to introduce it. But no worries if that's not the case!
